spring:
  application:
    name: stripe-checkout
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
    username: postgres.cadqqprndmbbwowcgnhm
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

stripe:
  api:
    secret-key: ${STRIPE_API_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}
app:
  domain: https://incalabria.net

email:
  name: InCalabria
  from: info@incalabria.net
  to: near.app.info@gmail.com
